# Generated by Django 2.1.1 on 2019-12-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField()),
                ('operating_system', models.CharField(max_length=50)),
            ],
        ),
    ]
