# Generated by Django 3.0.4 on 2020-03-16 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200313_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='is_main',
            field=models.BooleanField(default=True),
        ),
    ]
