# Generated by Django 2.2.9 on 2020-03-20 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_relationship_is_main'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='thematic',
            new_name='scopes',
        ),
    ]
