# Generated by Django 2.2.9 on 2020-03-23 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20200320_2240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relationship',
            options={},
        ),
        migrations.RenameField(
            model_name='thematics',
            old_name='name',
            new_name='topic',
        ),
        migrations.AddField(
            model_name='thematics',
            name='is_main',
            field=models.BooleanField(default=True),
        ),
    ]
