# Generated by Django 2.2.9 on 2020-03-23 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20200323_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationship',
            name='is_main',
        ),
    ]
