# Generated by Django 2.2.9 on 2020-03-23 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_remove_relationship_is_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='is_main',
            field=models.BooleanField(default=True),
        ),
    ]
