# Generated by Django 2.2.9 on 2020-04-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_auto_20200323_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thematics',
            name='is_main',
        ),
        migrations.AddField(
            model_name='thematics',
            name='topic2',
            field=models.TextField(default=0, max_length=30, verbose_name='Раздел2'),
        ),
    ]
